import Head from "next/head";
import Image from "next/image";
import { HomeHeader } from "../components/Headers";
import { BlackButton, WhiteButton } from "../components/Buttons";
import styles from "../styles/Home.module.css";
import MediaContent from "../components/MediaContent";
import InfoSlider from "../components/sliders/InfoSlider";
import LordIcon from "../components/LordIcon";

const slideData = [
  {
    src: "/images/Circular food.jpg",
    heading: `Curti's Resturant Website`,
    description: "A delightful resturant experience replicated on the internet",
  },
  // {
  //   src: "/images/Circular food.jpg",
  //   heading: `Amara Boutique Website`,
  //   description:
  //     "Elegant and classy, chic and savvy. A website that wear'sit's brand well",
  // },
  // {
  //   src: "/images/Circular food.jpg",
  //   heading: `Ogosam Petroluem Website`,
  //   description:
  //     "Power is a serious business, and deserves a seriously good website",
  // },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Softbue Sites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader />
      <MediaContent
        bg="#faf2fd"
        customClassName="column"
        heading="Not sure you need a website ?"
        content={
          <>
            <p>
              Is having a website necessary for your business? Well, you are
              here, so you must think so. <br />
              Over a short chat conversation I should be able to help you
              decide. For free of course.
            </p>{" "}
            <p>
              {" "}
              I won't try to pitch you my business, I will only help you
              understand what it is that your business needs right now. if it's
              a website, better for me and you
            </p>
            <WhiteButton>Let's Talk</WhiteButton>
          </>
        }
        media={
          <div>
            <Image
              src="/images/Circular food.jpg"
              alt=""
              width="400"
              height="300"
              // layout="fixed"
            />
          </div>
        }
      />

      <div className="block">
        <h2>Our Web Design Process</h2>
      </div>

      <MediaContent
        bg="#fdfaf2"
        customClassName="stack-animate process-cards"
        heading="Introductory Talk"
        content={
          <p>
            At this stage, we discuss your business needs, goals, strengths,
            competition, the problems it is facing and what you hope to achieve
          </p>
        }
        media={<LordIcon src="zpxybbhl" />}
      />

      <MediaContent
        bg="#f2f7fd"
        customClassName="stack-animate process-cards"
        heading="Industry Research"
        content={
          <p>
            Once we have an idea of what you want for your business, we conduct
            industry research and analysis to nderstand what you need in a
            product (website, application, app) to stand out from the
            competition
          </p>
        }
        media={<LordIcon src="soseozvi" />}
      />

      <MediaContent
        bg="#f2fdf4"
        customClassName="stack-animate process-cards"
        heading="Product Design"
        content={
          <p>
            At this stage, all our research and planning will become visible
            solutions in wireframes and prototypes designed to solve your
            problem perfectly
          </p>
        }
        media={<LordIcon src="rwotyanb" delay="1000" />}
      />

      <MediaContent
        bg="#faf2fd"
        customClassName="stack-animate process-cards"
        heading="Development"
        content={
          <p>
            Leave this stage to us. While you anticipate, we would be working at
            every possible hour to bring your approved design to life
          </p>
        }
        media={<LordIcon src="fqrjldna" delay="500" />}
      />

      <div className="block">
        <p>Ready to get your very own website or Application?</p>
        <BlackButton>Let's Get Started</BlackButton>
      </div>

      <div className="block">
        <h2>Explore Our Work</h2>
        <InfoSlider data={slideData} />
      </div>
    </div>
  );
}

{
  /* <script src="https://cdn.lordicon.com/lusqsztk.js"> 
<lord-icon
  src="https://cdn.lordicon.com/zpxybbhl.json"
  trigger="loop"
  colors="primary:#121331,secondary:#08a88a"
  stroke="15"
  scale="75"
  style={{ width: "100px", height: "100px" }}
></lord-icon>
<lord-icon
  src="https://cdn.lordicon.com/soseozvi.json"
  trigger="loop"
  colors="primary:#121331,secondary:#08a88a"
  stroke="15"
  style={{ width: "100px", height: "100px" }}
></lord-icon>
<script src="https://cdn.lordicon.com/lusqsztk.js"> 
<lord-icon
  src="https://cdn.lordicon.com/joeivjls.json"
  trigger="loop"
  delay="10"
  colors="primary:#121331,secondary:#08a88a"
  stroke="15"
  style={{ width: "100px", height: "100px" }}
></lord-icon> 
     
  <lord-icon
    src="https://cdn.lordicon.com/iltqorsz.json"
    trigger="loop"
    colors="primary:#121331,secondary:#66eece"
    stroke="15"
    style={{ width: "150px", height: "150px" }}
  ></lord-icon>
    
*/
}
